name: Register images with Connect server

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: select a target environment

jobs:
  publish:
    strategy:
      matrix:
        PYTHON_VERSION: ["3.9.21", "3.10.16", "3.11.11", "3.12.7", "3.13.1"]
        QUARTO_VERSION: ["1.5.56", "1.6.40"]
        R_VERSION: ["4.0.5", "4.1.3", "4.2.3", "4.3.3", "4.4.2"]
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Publish
        env:
          PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
          QUARTO_VERSION: ${{ matrix.QUARTO_VERSION }}
          R_VERSION: ${{ matrix.R_VERSION }}
          CONNECT_SERVER: ${{ vars.CONNECT_SERVER }}
          CONNECT_API_KEY: ${{ secrets.CONNECT_API_KEY }}
        run: |
          deno run --allow-env --allow-net publish.ts
