name: Register images with Connect server

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: select a target environment

jobs:
  get-versions:
    uses: ./.github/workflows/versions.yml

  publish:
    needs: get-versions
    strategy:
      matrix:
        PYTHON_VERSION: ${{fromJson(needs.get-versions.outputs.python)}}
        QUARTO_VERSION: ${{fromJson(needs.get-versions.outputs.quarto)}}
        R_VERSION: ${{fromJson(needs.get-versions.outputs.r)}}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Publish
        env:
          PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
          QUARTO_VERSION: ${{ matrix.QUARTO_VERSION }}
          R_VERSION: ${{ matrix.R_VERSION }}
          CONNECT_SERVER: ${{ vars.CONNECT_SERVER }}
          CONNECT_API_KEY: ${{ secrets.CONNECT_API_KEY }}
        run: |
          deno run --allow-env --allow-net publish.ts
