name: Build and Publish to GHCR

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        PYTHON_VERSION: ["3.10.17", "3.11.12", "3.12.10", "3.13.3"]
        QUARTO_VERSION: ["1.7.31"]
        R_VERSION: ["4.2.3", "4.3.3", "4.4.3", "4.5.0"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            PYTHON_VERSION=${{ matrix.PYTHON_VERSION }}
            QUARTO_VERSION=${{ matrix.QUARTO_VERSION }}
            R_VERSION=${{ matrix.R_VERSION }}
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/edavidaja/pqr:python${{ matrix.PYTHON_VERSION }}-quarto${{ matrix.QUARTO_VERSION }}-r${{ matrix.R_VERSION }}

