name: Version matrix
on:
  workflow_call:
    outputs:
      python:
        description: "Python versions array"
        value: ${{ jobs.versions.outputs.python }}
      quarto:
        description: "Quarto versions array" 
        value: ${{ jobs.versions.outputs.quarto }}
      r:
        description: "R versions array"
        value: ${{ jobs.versions.outputs.r }}

jobs:
  versions:
    runs-on: ubuntu-latest
    outputs:
      python: '["3.10.20", "3.11.15", "3.12.13", "3.13.13", "3.14.4"]'
      quarto: '["1.9.37"]'
      r: '["4.2.3", "4.3.3", "4.4.3", "4.5.3", "4.6.0"]'
    steps:
      - name: Load versions
        run: echo "Version definitions loaded"
