name: Version matrix
on:
  workflow_call:
    outputs:
      python:
        description: "Python versions array"
        value: ${{ jobs.versions.outputs.python }}
      quarto:
        description: "Quarto versions array" 
        value: ${{ jobs.versions.outputs.quarto }}
      r:
        description: "R versions array"
        value: ${{ jobs.versions.outputs.r }}

jobs:
  versions:
    runs-on: ubuntu-latest
    outputs:
      python: '["3.10.19", "3.11.14", "3.12.11", "3.13.11", "3.14.2"]'
      quarto: '["1.8.27"]'
      r: '["4.2.3", "4.3.3", "4.4.3", "4.5.2"]'
    steps:
      - name: Load versions
        run: echo "Version definitions loaded"
